---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[curl]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[curl]

suites:
  - name: default
    run_list:
      - recipe[redx::install]
    attributes:
      redis:
        source:
          url: "http://download.redis.io/releases"
